"""
This type stub file was generated by pyright.
"""

from .version import __version__
from .error import *
from .enums import *
from .base import *
from .gobject import *
from .gvalue import *
from .vobject import *
from .vinterpolate import *
from .vconnection import *
from .vsource import *
from .vsourcecustom import *
from .vtarget import *
from .vtargetcustom import *
from .voperation import *
from .vimage import *
from .vregion import *
from logging import Logger
from typing import Any, Dict, Optional

logger: Logger
API_mode: bool

major: Optional[int]
minor: Optional[int]
micro: Optional[int]
features: Optional[Dict[str, Any]]

class GLogLevelFlags:
    FLAG_RECURSION: int
    FLAG_FATAL: int
    LEVEL_ERROR: int
    LEVEL_CRITICAL: int
    LEVEL_WARNING: int
    LEVEL_MESSAGE: int
    LEVEL_INFO: int
    LEVEL_DEBUG: int
    LEVEL_TO_LOGGER: int


_log_handler_cb: base.CData
_log_handler_id: base.CData
_remove_handler: base.CData
__all__ = ['Error', 'Image', 'Region', 'Introspect', 'Operation', 'GValue', 'Interpolate', 'GObject', 'VipsObject', 'type_find', 'type_name', 'version', '__version__', 'at_least_libvips', 'API_mode', 'get_suffixes', 'cache_set_max', 'cache_set_max_mem', 'cache_set_max_files']
