"""
This type stub file was generated by pyright.
"""

import pyvips
from cffi import FFI

class Interpolate(pyvips.VipsObject):
    """Make interpolators for operators like :meth:`.affine`.

    """
    def __init__(self, pointer: FFI.CData) -> None:
        ...
    
    @staticmethod
    def new(name: str) -> Interpolate:
        """Make a new interpolator by name.

        Make a new interpolator from the libvips class nickname. For example::

            inter = pyvips.Interpolator.new('bicubic')

        You can get a list of all supported interpolators from the command-line
        with::

            $ vips -l interpolate

        See for example :meth:`.affine`.

        """
        ...
    


__all__ = ['Interpolate']
