"""
This type stub file was generated by pyright.
"""

import pyvips

class Region(pyvips.VipsObject):
    """Wrap a VipsRegion object.

    """
    def __init__(self, pointer) -> None:
        ...
    
    @staticmethod
    def new(image): # -> Region:
        """Make a region on an image.

        Returns:
            A new :class:`.Region`.

        Raises:
            :class:`.Error`

        """
        ...
    
    def width(self):
        """Width of pixels held by region."""
        ...
    
    def height(self):
        """Height of pixels held by region."""
        ...
    
    def fetch(self, x, y, w, h):
        """Fill a region with pixel data.

        Pixels are filled with data!

        Returns:
            Pixel data.

        Raises:
            :class:`.Error`

        """
        ...
    


__all__ = ['Region']
