"""
This type stub file was generated by pyright.
"""

import pyvips
from cffi import FFI

class Region(pyvips.VipsObject):
    """Wrap a VipsRegion object.

    """
    def __init__(self, pointer: pyvips.CData) -> None:
        ...
    
    @staticmethod
    def new(image: pyvips.Image) -> Region:
        """Make a region on an image.

        Returns:
            A new :class:`.Region`.

        Raises:
            :class:`.Error`

        """
        ...
    
    def width(self) -> int:
        """Width of pixels held by region."""
        ...
    
    def height(self) -> int:
        """Height of pixels held by region."""
        ...
    
    def fetch(self, x: int, y: int, w: int, h: int) -> FFI.buffer:
        """Fill a region with pixel data.

        Pixels are filled with data!

        Returns:
            Pixel data.

        Raises:
            :class:`.Error`

        """
        ...
    


__all__ = ['Region']
