from typing import Any

REQUIRED: Any = object()

DECORATOR_ATTR_COMPUTE_FIELD: str = "_COMPUTE_FIELD"
DECORATOR_ATTR_FORWARD_FIELD: str = "_FORWARD_FIELD"
DECORATOR_ATTR_POST_EFFECT: str = "_POST_EFFECT"